#!/bin/bash

# CONFIGURATION
INSTALL_DIR=/usr/lib/aolmanager
DEVICE=`cat /system/build.prop | grep ro.product.model | awk -F'=' '{print $2}'`

# DIALOG
DIALOG_CANCEL=1
HEIGHT=15
WIDTH=50
LHEIGHT=10

# COLOR CODE
RED='\033[0;31m'
NC='\033[0m'
YELLOW='\033[0;33m'

# CHECK DIALOG INSTALL
if [ ! -f /usr/bin/dialog ]; then
	echo -e "${RED}[info]${NC}dialog not installed..."
	apt-get update && apt-get install dialog -y
	echo -e "${YELLOW}[info]${NC}dialog installed..."
fi

# MAIN MENU
function mainmenu() {

	exec 3>&1	
	MAINSEL=$(dialog --backtitle "AndroidOverLinux Manager" \
		--menu "aolmanager on [$DEVICE]" $HEIGHT $WIDTH $LHEIGHT \
		"[1]" "System Information" \
		"[2]" "Basic Configuration" \
		"[3]" "Service Management" \
		"[4]" "Install Service" \
		"[5]" "Uninstall Service" \
		"[6]" "Miscelaeous System Tweak" 2>&1 1>&3)
	
	exit_status=$?
	exec 3>&-	

	if [ "$exit_status" == "$DIALOG_CANCEL" ]; then
		clear
		exit 0
	fi
	
	case  $MAINSEL in
		"[1]") 
			;;
		"[2]")
			;;
		"[3]") 
			;;
		"[4]")
			;;
		"[5]")
			;;
		"[6]")
			;;
		*)
			echo $MAINSEL
			sleep 3
			;;
	esac
}

# 1. System Information



# aolmanager MAIN

while true; do 
	mainmenu
done

